//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalleryApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Art
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Art()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public string genre { get; set; }
        public int idTypeSize { get; set; }
        public string size { get; set; }
        public decimal price { get; set; }
        public int idExibition { get; set; }
        public string Decription { get; set; }
        public string PhotoName { get; set; }
        public byte[] ProductPhoto { get; set; }
        public string Comments { get; set; }
        public Nullable<int> IdWorker { get; set; }
    
        public virtual Exibition Exibition { get; set; }
        public virtual TypeSize TypeSize { get; set; }
        public virtual Workers Workers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
