//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalleryApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lamp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lamp()
        {
            this.Order = new HashSet<Order>();
            this.Order1 = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string ModelName { get; set; }
        public string Manufacturer { get; set; }
        public int LampTypeId { get; set; }
        public double PowerWatts { get; set; }
        public int ColorTemperature { get; set; }
        public double CRI { get; set; }
        public int LuminousFlux { get; set; }
        public int BeamAngle { get; set; }
        public bool HasUVProtection { get; set; }
        public bool HasIRProtection { get; set; }
        public bool Dimmable { get; set; }
        public int MountingTypeId { get; set; }
        public double Voltage { get; set; }
        public decimal Price { get; set; }
        public int StockQuantity { get; set; }
        public string Description { get; set; }
        public string PhotoName { get; set; }
        public byte[] ProductPhoto { get; set; }
    
        public virtual LampType LampType { get; set; }
        public virtual MountingType MountingType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order1 { get; set; }
    }
}
