//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalleryApp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gallerydatabaseEntities : DbContext
    {
        private static gallerydatabaseEntities _context;
        public gallerydatabaseEntities()
            : base("name=gallerydatabaseEntities")
        {
        }
        public static gallerydatabaseEntities GetContext()
        {
            if (_context == null)
            {
                _context = new gallerydatabaseEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Art> Art { get; set; }
        public virtual DbSet<Exibition> Exibition { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<ShippingType> ShippingType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeSize> TypeSize { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WorkerInfo> WorkerInfo { get; set; }
    }
}
