//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalleryApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdArt { get; set; }
        public string Comment { get; set; }
        public string Adress { get; set; }
        public int IdShippingType { get; set; }
    
        public virtual Art Art { get; set; }
        public virtual ShippingType ShippingType { get; set; }
    }
}
